### PR TITLE
Fixed Add/Edit Expenses feature 

### LINKED ISSUE #41: Fix bugs in add/edit expense (recurring)

### PR DESCRIPTION
**Pull request by luluwuwu**
fixed bugs for recurring expenses, category assignments for expenses etc.

### CODE REVIEW

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 1]
```diff
@@ -58,37 +57,36 @@ public ExpenseOD addExpenseInMonth(ExpenseID expenseIDAdd) throws EntityExceptio
...
             Category selectedCategory = findCategory(categoryList, expenseID.getOldCategory());
-            Category other = findCategory(categoryList, "Other");
 
             if (valueDouble < 0) {
-                // 2. Expense budget less than 0 fail
+                // 2. Expense value less than 0 fail
                 ExpenseOD expenseODFailAdd = new ExpenseOD("Expense value can't be less than $0. Please try again!");
                 return expenseOB.fail(expenseODFailAdd);
             }
-            for (Expense expense1 : monthExpenseList) {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:68]: This should not be deleted. This block of code checks if the expense name already exists in that month, and is applicable regardless of if they are choosing recurringExpense or not.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 2]
```diff
@@ -58,37 +57,36 @@ public ExpenseOD addExpenseInMonth(ExpenseID expenseIDAdd) throws EntityExceptio
...
-                if (expense1.getName().equals(expenseID.getName())) {
-                    //Repeated name in month
-                    ExpenseOD expenseODFailEdit = new ExpenseOD("There is already a expense with this new name in this month.");
-                    return expenseOB.fail(expenseODFailEdit);
-                }
-            }
-
             if (expenseID.getIsRecurringExpense()) {
                 if(recurringExpenseList.size() > 0) {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: You don't need this entire if statement. Recurring expenses are recurring because they occur in the monthly storage of EVERY month. So we don't need this if statement, since if the new name is unique in that month, it is unique in the recurring expense list too.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 3]
```diff
@@ -58,37 +57,36 @@ public ExpenseOD addExpenseInMonth(ExpenseID expenseIDAdd) throws EntityExceptio
...
+            }
+            for (Expense expense1 : monthExpenseList) {
+                if (expense1.getName().equals(expenseID.getName())) {
+                    //Repeated name in month
+                    ExpenseOD expenseODFailEdit = new ExpenseOD("There is already a expense with this new name in this month.");
+                    return expenseOB.fail(expenseODFailEdit);
+                }
+            }
 
             Expense newExpense = new Expense(expenseID.getName(), selectedCategory,valueDouble);
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Everything else above the catch statements should be in an else block for clarity.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 4]
```diff
@@ -131,76 +129,75 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
         MonthlyStorage month = session.getMonthlyData(expenseID.getMonthID());
         ArrayList<Expense> monthExpenseList = month.getExpenseData();
         ArrayList<Category> categoryList = month.getCategoryData();
-        Expense selectedExpense;
 
         try {
             Category selectedCategory = findCategory(categoryList, expenseID.getOldCategory());
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: I would rename this, considering "getOldCategory" actually gets the new category of the expense.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 5]
```diff
@@ -131,76 +129,75 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
...
+                if(checkHaveSameNameInList(monthExpenseList, expenseID.getName())) {
+                    // Repeated name fail: When a user tries to edit the expense name to a existing expense in month.
                     ExpenseOD expenseODFailEdit = new ExpenseOD("There is already a expense with this new name in this month.");
                     return expenseOB.fail(expenseODFailEdit);
                 }}
-            if (changeInRecurringInfo()) {// 4. Same recurring expense name fail
                 if (expenseID.getIsRecurringExpense()) {
-                    if (checkHaveSameNameInList(recurringExpenseList)) {
+                    //Repeated recurring expense name fail: When a user tries to edit the current expense to a recurring expense but the name already exist as a recurring expense.
+                    if (checkHaveSameNameInList(recurringExpenseList,expenseID.getName())) {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: This is checked above when you are checking the expenses in the month!

Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: So you can delete everything in this if statement, also we don't need that output data message since its redundant to the one above about the same name.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 6]
```diff
@@ -131,76 +129,75 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
...
+            }
             if(!Objects.equals(expenseIDEdit.getName(), expenseIDEdit.getOldExpense())){
-                if(checkHaveSameNameInList(monthExpenseList)) {
-                    //1. Repeated name fail
+                if(checkHaveSameNameInList(monthExpenseList, expenseID.getName())) {
+                    // Repeated name fail: When a user tries to edit the expense name to a existing expense in month.
                     ExpenseOD expenseODFailEdit = new ExpenseOD("There is already a expense with this new name in this month.");
                     return expenseOB.fail(expenseODFailEdit);
                 }}
-            if (changeInRecurringInfo()) {// 4. Same recurring expense name fail
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:155]: I actually think you could keep this line, it helps tell you whether or not there is a change, making other code redundant (like the name check in the recurring list can be removed because we already know the expense was not recurring before).

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 7]
```diff
@@ -131,76 +129,75 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
...
+                        session.addRecurExpense(selectedExpense);
                         selectedExpense.setCategory(selectedCategory);
-                        ExpenseOD expenseODSuccessEditRecurring = new ExpenseOD("You have updated all changes of this expense to the category selected in current month!");
-                        return expenseOB.success(expenseODSuccessEditRecurring);
-                    }
-                }else {
+                        // Success edit to new recurring expense.
+                        ExpenseOD expenseODSuccessEditRecurring = new ExpenseOD("You have updated all changes of this new recurring expense!");
+                        return expenseOB.success(expenseODSuccessEditRecurring);}
+                }else if(checkHaveSameNameInList(recurringExpenseList, expenseID.getOldExpense())&& !expenseIDEdit.getIsRecurringExpense()) {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: You can just have an else statement here since we know that isRecurring is false and it used to be true (because we are keeping the if change in recurring statement), all we have to do is modify the changes and delete the expense from recurring.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 8]
```diff
@@ -131,76 +129,75 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
...
-                    ExpenseOD expenseODSuccessEditRecurring = new ExpenseOD("You have updated all changes of this expense to a recurring expense in current session!");
+                    session.deleteRecurExpense(expenseID.getName());
+                    selectedExpense.setCategory(selectedCategory);
+                    //Success edit to remove recurring expense.
+                    ExpenseOD expenseODSuccessEditRecurring = new ExpenseOD("You have updated all changes of this expense and it is no longer a recurring expense!");
                     return expenseOB.success(expenseODSuccessEditRecurring);
                 }
-                    }
 
             selectedExpense.setName(expenseIDEdit.getName());
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: For clarity, everything above the catch should be in an else clause.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 9]
```diff
@@ -227,33 +225,14 @@ public Category findCategory (ArrayList < Category > monthCategoryData, String n
             throw new NoSuchElementException();
         }
 
-    /**
-     * Identifying the only two cases when Session.recurringExpenseData needs to updated when attempting to edit Expense.
-     * (The user changes their response for the isRecurringExpense checkbox)
-     * @return boolean suggesting there is a need to update Session.recurringExpenseData
-     */
-    private boolean changeInRecurringInfo() {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:235]: Please keep this I think this method is really great and helps keep code simpler in the main method!!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 8 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Also, notice how you have the same three lines of code repeated wherever you are editing an expense? You could make an editExpense() private helper method with those three set_ lines and that would make the code up here cleaner!

**Review by katarinaavucic — CHANGES_REQUESTED** [review]
Overall it is looking better and you had a lot of the same ideas as I did! There are some issues with the way you are checking recurring expenses still, so I tried to clarify as best as I could. Also here is the general structure I was thinking for the code in pseudocode:

try clause in add:
if valuedouble...
for expense in monthExpenseList...
if is recurring... (we need to create expense and add to month and session)
else... (we need to create expense and add to month only)
** alternatively you could have the if recurring after you create and add to month so that if its recurring it will add to session.

try clause in edit:
if valuedouble...
if equals getName oldExpenseGetName...
if change in recurring...
     if is recurring.... (we know that expense should be edited and added to recurExpense)
     else... (we know that expense should be edited and removed from recurExpense)
else (we know expense only needs to be edited)

Hope that helps!

File: src/main/java/views/add_edit_epense_views/AddExpenseV.java
Comment (YinLingithub) [inline src/main/java/views/add_edit_epense_views/AddExpenseV.java:1]: Line 71. Set HIDE_ON_CLOSE

File: src/main/java/views/add_edit_epense_views/AddExpenseV.java [hunk 10]
```diff
@@ -24,14 +23,15 @@ public class AddExpenseV extends Component implements ActionListener, LoadMonthM
     private final JComboBox<String> categoryCombo;
     private final String selectedExpense;
     private String selectedCategory;
-    private JCheckBox isRecurringCheckBox;
+    private final JCheckBox isRecurringCheckBox = new JCheckBox("This is a recurring expense.");
```
Comment (YinLingithub) [inline src/main/java/views/add_edit_epense_views/AddExpenseV.java]: I was testing the view, and I think having a whole sentence commenting the check box may be too long. Make it shorter, like "Is recurring expense".

File: src/main/java/views/add_edit_epense_views/EditExpenseV.java [hunk 11]
```diff
@@ -33,18 +33,20 @@ public class EditExpenseV extends Component implements ActionListener, LoadMonth
```
Comment (YinLingithub) [inline src/main/java/views/add_edit_epense_views/EditExpenseV.java:34]: Same here, maybe make the checkbox comment shorter.

File: src/main/java/views/add_edit_epense_views/EditExpenseV.java
Comment (YinLingithub) [inline src/main/java/views/add_edit_epense_views/EditExpenseV.java:1]: Line 73 or 75: HIDE_ON_CLOSE

**Review by YinLingithub — COMMENTED** [review]
You should also add
`panel.add(submit);`
in openEditCategory() of EditCategoryV (around line 70)

File: src/main/java/views/add_edit_epense_views/AddExpenseV.java [hunk 12]
```diff
@@ -24,14 +23,15 @@ public class AddExpenseV extends Component implements ActionListener, LoadMonthM
     private final JComboBox<String> categoryCombo;
```
Comment (YinLingithub) [inline src/main/java/views/add_edit_epense_views/AddExpenseV.java:24]: You would need to extend JFrame instead of Component for your JOptionPane.showMessageDialog() to work. This also applies to EditExpenseV, AddCategoryV, EditCategoryV. 

Since we have all classes merged now, you should run Main.java to test your view.

**Comment by YinLingithub** [comment]
This is what you need to change in AddCategoryV and EditCategoryV. 

[https://github.com/CSC207-2023Y-UofT/course-project-DoorKeepers/commit/6dd16641f436d9759cb74b06ac76236ad9ff4e5b](url)

[https://github.com/CSC207-2023Y-UofT/course-project-DoorKeepers/commit/4055e63155e81a7d5680e985675a87d07acc2dbe](url)

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 2 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Got it. It took me a while to think about what to write for this failed message and it still turns out awkward, so actually kinda glad that we won't use it. ahah

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 1 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:68]: What you're saying makes sense.

Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:68]: They're just moved under from lines 82-89

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 3 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: I think I'll just have the ExpenseOD instantiation and the return outside, it shows an error for not having a return statement, and we know it's not part of the exceptions that we're dealing with!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 1 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java:68]: Yup, I saw! but instead the should be checked where I specified above, since if they are checked below you are not checking the recurring expenses (you are checking in the recurExpense list which is redundant, so if you move this code block back it works better!).

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 4 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: I'm refactoring all of them to "category". (getCategory() etc. )

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 2 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: LOL no worries! Honestly, this task was pretty daunting so I understand youuu.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 3 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Sounds good!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 7 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Oh yes

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 8 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: That sounds like a good idea

File: src/main/java/views/add_edit_epense_views/AddExpenseV.java
Comment (luluwuwu) [reply src/main/java/views/add_edit_epense_views/AddExpenseV.java:1]: right tks

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 4 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Nice!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 3 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Nvm the last if statement has an else, so these lines will have to be independent

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 8 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Thanks! :D you could probably do a similar thing for adding as well!

Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: I looked at it for addExpense, but it will just be two lines of code and it will have to pass in the same amount of parameters. So I think I'll just leave it as is! (Also one of them will be MonthlyStorage.addeEpense() which is going to throw an entityException and I will like to avoid it at all costs lol)

Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: Sounds good!! Omg real the EntityException there has gotten so annoying so yeah best to leave it out!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 3 above)
Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: I see what the confusion is here, I am suggesting to move the for loop back where it was (it needs to be there otherwise we arent checking for the same name in the recurring expenses) and then have this code go in the else block that comes after the if is recurring expense. Like how i said it in the overall comment! But i think the reason why you are saying there is no else is because the for loop is between the code (unless I am misunderstanding!).

Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: No yah you're right I moved the previous lines into the wrong else, now they are in the else.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 13]
```diff
@@ -53,70 +47,47 @@ public ExpenseOD addExpenseInMonth(ExpenseID expenseIDAdd) throws EntityExceptio
...
-                // 2. Expense value less than 0 fail
+                //Expense value less than 0 fail: When a user tries to add the expense value with a negative number.
                 ExpenseOD expenseODFailAdd = new ExpenseOD("Expense value can't be less than $0. Please try again!");
-                return expenseOB.fail(expenseODFailAdd);
-            }
+                return expenseOB.fail(expenseODFailAdd);}
             if (expenseID.getIsRecurringExpense()) {
                 if(recurringExpenseList.size() > 0) {
-                    for (Expense expense1 : recurringExpenseList) {
+                    for (Expense expense1 : monthExpenseList) {
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: This for loop should be above line 56. Currently it is only checking for if an expense has the same name if the expense is recurring and there are recurring expenses, which should not happen. Additionally, you should get rid of the if statement in line 57, because it prevents recurring expenses from being added if no recurring expenses exist, which means the user would never be able to add a recurring expense.

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java [hunk 14]
```diff
@@ -130,53 +101,34 @@ public ExpenseOD editExpenseInMonth(ExpenseID expenseIDEdit) throws EntityExcept
...
-                }else if(checkHaveSameNameInList(recurringExpenseList, expenseID.getOldExpense())&& !expenseIDEdit.getIsRecurringExpense()) {
-                    selectedExpense.setName(expenseIDEdit.getName());
-                    expenseIDEdit.setValue(valueDouble);
-                    selectedExpense.setValue(valueDouble);
+                    setEditInfo(expenseID, valueDouble, selectedExpense,selectedCategory);
+                    session.addRecurExpense(selectedExpense);
+                    // Success edit to new recurring expense.
+                    ExpenseOD expenseODSuccessEditRecurring = new ExpenseOD("You have updated all changes of this new recurring expense!");
+                    return expenseOB.success(expenseODSuccessEditRecurring);
+                }else if (checkHaveSameNameInList(recurringExpenseList, expenseID.getOldExpense())){
```
Comment (katarinaavucic) [inline src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: This shouldn't be an else if, it should just be else! Otherwise this block won't run because it has already been failed above when checking for the same name. But other than that minor change this method is good!

Comment (katarinaavucic) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: This else runs when the expense was recurring but now is not! That's why we are deleting it from recurExpense.

**Review by katarinaavucic — CHANGES_REQUESTED** [review]
YAYYYY I think we are almost at the non-buggy implementation!!

File: src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java (hunk 14 above)
Comment (luluwuwu) [reply src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java]: You're right

**Review by katarinaavucic — DISMISSED** [review]
YAYYYYYYY!!! It should work now, just verify that it runs on all of your tests :D.

**Review by katarinaavucic — APPROVED** [review]
YAYY everything works!

**Review by YinLingithub — APPROVED** [review]
Good job, Lulu and Kat!!!

**Review by aricasas — APPROVED** [review]
Nice job!
